spring.application.name=trustops-backend
management.endpoints.web.exposure.include=health,info
spring.datasource.url=jdbc:postgresql://localhost:5432/trustops
spring.datasource.username=trustops
spring.datasource.password=trustops

spring.jpa.hibernate.ddl-auto=update
